version: "3.8"

services:
  db:
    image: mariadb:10.2.10
    command:
      [
        "--character-set-server=utf8mb4",
        "--skip-character-set-client-handshake",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    container_name: app_db
    restart: always
    ports:
      - 3306:3306
    volumes:
      #volumes : container 상의 Data를 host machine과 공유하기 위한 기능입니다. volumes는 host_path:container_path 로 값을 입력할 수 있습니다.
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul

  be:
    build:
      dockerfile: Dockerfile
      context: ./BE
    container_name: app_backend
    volumes:
      - ./BE:/app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  nginx:
    # Since our Dockerfile for web-server is located in react-app foler, our build context is ./react-app
    build: ./front
    container_name: nginx
    volumes:
      - /app/node_modules
      - ./front:/react-app
    ports:
      - "80:8080"
    depends_on:
      - be
